### ISSUE TITLE
figure doesn't display in Firefox-based Jupyter

### ISSUE THREAD

**Issue by abdlg** [talgalili/heatmaply#176] opened 2018-05-18 13:45 UTC
I have noticed that the figures couldn't be displayed in the Firefox web browser when using the R kernel in Jupyter, but with Chrome it is working fine. 

thanks

**Comment by Alanocallaghan** [comment] 2018-05-18 14:11
Could you post an example, just to make it easier to debug? Thanks

**Comment by koalive** [comment] 2018-07-24 08:17
Hi,  
I observe the same behavior. A simple:
`heatmaply(cor(iris[,-5]))`
does not display anything in my notebook (and no error message) with firefox (61.0.1) but works as expected with Chrome (67.0.3396.99).  
You can find my sessionInfo() output below.
Cheers!

> R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1
Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] heatmaply_0.15.2   viridis_0.5.1      viridisLite_0.3.0  plotly_4.7.1      
[5] ggplot2_3.0.0.9000
loaded via a namespace (and not attached):
 [1] httr_1.3.1           tidyr_0.8.1          jsonlite_1.5        
 [4] foreach_1.4.4        gtools_3.5.0         shiny_1.1.0         
 [7] assertthat_0.2.0     stats4_3.4.1         yaml_2.1.19         
[10] robustbase_0.93-0    pillar_1.2.3         lattice_0.20-35     
[13] glue_1.2.0           uuid_0.1-2           digest_0.6.15       
[16] promises_1.0.1       RColorBrewer_1.1-2   colorspace_1.3-2    
[19] httpuv_1.4.3         htmltools_0.3.6      plyr_1.8.4          
[22] pkgconfig_2.0.1      xtable_1.8-2         purrr_0.2.5         
[25] mvtnorm_1.0-8        scales_0.5.0.9000    webshot_0.5.0       
[28] gdata_2.18.0         whisker_0.3-2        later_0.7.2         
[31] tibble_1.4.2         withr_2.1.2          repr_0.15.0         
[34] nnet_7.3-12          lazyeval_0.2.1       mime_0.5            
[37] magrittr_1.5         crayon_1.3.4         mclust_5.4          
[40] evaluate_0.10.1      MASS_7.3-50          gplots_3.0.1        
[43] class_7.3-14         tools_3.4.1          registry_0.5        
[46] data.table_1.11.4    trimcluster_0.1-2    stringr_1.3.1       
[49] kernlab_0.9-26       munsell_0.5.0        cluster_2.0.7-1     
[52] fpc_2.1-11           bindrcpp_0.2.2       compiler_3.4.1      
[55] caTools_1.17.1       rlang_0.2.1          grid_3.4.1          
[58] pbdZMQ_0.3-3         iterators_1.0.9      IRkernel_0.8.12.9000
[61] htmlwidgets_1.2      crosstalk_1.0.0      labeling_0.3        
[64] bitops_1.0-6         base64enc_0.1-3      gtable_0.2.0        
[67] codetools_0.2-15     flexmix_2.3-14       reshape2_1.4.3      
[70] TSP_1.1-6            R6_2.2.2             seriation_1.2-3     
[73] gridExtra_2.3        prabclus_2.2-6       dplyr_0.7.5         
[76] bindr_0.1.1          KernSmooth_2.23-15   dendextend_1.8.0    
[79] modeltools_0.2-21    stringi_1.2.3        IRdisplay_0.5.0     
[82] Rcpp_0.12.17         gclus_1.3.1          DEoptimR_1.0-8      
[85] tidyselect_0.2.4     diptest_0.75-7

**Comment by Alanocallaghan** [comment] 2018-07-24 09:18
Could you share a link to an example @koalive? I'm not too familiar with Jupyter

**Comment by koalive** [comment] 2018-07-24 13:42
[See this example.](https://github.com/koalive/heatmaplyNotebook/blob/master/Example.ipynb) 
It seems that the heatmaps are not displayed in Github's preview anyway. But if I run this notebook locally, it is shown correctly in Chrome but not in Firefox.

**Comment by Alanocallaghan** [comment] 2018-07-24 14:12
Thanks! I'll have a look asap

**Comment by koalive** [comment] 2018-07-25 10:08
Thanks. Actually, the problem seems to be common to other htmlwidgets (I can see figures from [SigmaNet](https://github.com/iankloo/sigmaNet) and [BioCircos](https://github.com/lvulliard/BioCircos.R) in Jupyter notebooks in Chrome but not in Firefox) as well, so I'll probably do some more tests and report it there.

**Comment by Alanocallaghan** [comment] 2018-07-25 11:07
That was going to be my first port of call. Thanks

**Comment by talgalili** [comment] 2019-08-17 05:17
Is this bug related to heatmaply?
Can we close this issue?

**Comment by koalive** [comment] 2019-08-17 13:01
The issue still occurs, but all other htmlwidgets I use have the same behavior. Unless someone has a counter-example I guess you can assume the issue is on their side and close this thread.

**Comment by talgalili** [comment] 2019-08-17 13:29
Sounds reasonable, thanks for the report :)

**Closed by talgalili** 2019-08-17 13:29 UTC
