### ISSUE TITLE
Color for diagonal elements

### ISSUE THREAD

**Issue by kengcher** [talgalili/heatmaply#189] opened 2018-10-03 13:45 UTC
Hi is there a way to set the diagonal elements of a square matrix to be black in heatmaply?

Thank you.

**Comment by Alanocallaghan** [comment] 2018-10-03 15:34
This should work:
```{r}
m <- cor(mtcars)
diag(m) <- NA
heatmaply(m, na.value="000000", plot_method="plotly")
```
Unfortunately there's a bug in plotly that stops this from working (#11)

**Comment by carmensandoval** [comment] 2019-01-15 20:58
Hi,

I am having a similar issue which I posted [here](https://stackoverflow.com/questions/54195515/in-r-how-to-assign-a-value-to-a-specific-color-while-mapping-all-other-values). Looking for workarounds while this gets fixed in plotly .
```
heatmaply(diffexp.spread, na.color = "grey20")
```
  [2]: https://i.stack.imgur.com/8irS5.gif

[![enter image description here][2]][2]

Any help is appreciated.

**Comment by talgalili** [comment] 2019-08-17 05:15
Are there plans to introduce this to heatmaply?
If not, can we close this issue?

**Comment by Alanocallaghan** [comment] 2019-08-19 10:49
This is basically just a dupe of #11

**Closed by Alanocallaghan** 2019-08-19 10:49 UTC
