### ISSUE TITLE
[FEATURE] Allow for custom hovertext for annotations

### ISSUE THREAD

**Issue by cole-johanson** [talgalili/heatmaply#283] opened 2022-11-17 16:40 UTC
The custom_hovertext option does not apply to annotations.

```
mat <- mtcars
mat[] <- paste("This cell is", rownames(mat))
mat[] <- lapply(colnames(mat), function(colname) {
    paste0(mat[, colname], ", ", colname)
})
heatmaply(
  mtcars %>% mutate(cyl=as.character(cyl)),
  custom_hovertext = mat
)
# Note that the custom hovertext does not apply to `cyl`
```

It would be a nice feature if the custom hovertext could apply to annotations as well.

**Comment by Alanocallaghan** [comment] 2022-11-17 16:52
Duplicate of #268

**Closed by Alanocallaghan** 2022-11-17 16:52 UTC
Labels: enhancement
