### ISSUE TITLE
Heatmaply Downloading as a .PNG

### ISSUE THREAD

**Issue by jalalsiddiqui** [talgalili/heatmaply#187] opened 2018-08-29 13:37 UTC
When I try to download the heatmaply image as a png file, the first click gives me an empty outline of the heatmap.  Subsequent clicks are okay.  Is it possible to resolve this?

Also can heatmaply images be downloaded as pdf files?  Is there a function for that.  

We want to add this to our Shiny App

**Comment by Alanocallaghan** [comment] 2018-08-29 13:50
You mean the PNG button on the figure itself? That's a plotly issue I think, rather than one specific to heatmaply. Not sure the cause.

Downloading as PDF is possible with a paid plotly account, see here: https://plot.ly/python/static-image-export/

**Comment by Alanocallaghan** [comment] 2018-08-29 23:37
https://github.com/talgalili/heatmaply/issues/183

**Comment by talgalili** [comment] 2019-08-17 05:16
Can we close this issue?

**Comment by jalalsiddiqui** [comment] 2019-08-17 17:12
Yes Close it Sorry


Jalal

________________________________

**Comment by talgalili** [comment] 2019-08-17 17:21
Cool, 10x.

**Closed** 2019-08-17 17:20 UTC
