### ISSUE TITLE
Warning: unable to load shared object R_X11.so 

### ISSUE THREAD

**Issue by gtollefson** [talgalili/heatmaply#196] opened 2018-12-18 17:55 UTC
I receive the following warning when running the heatmaply() plotting function using heatmaply version 0.15.3 on R version 3.4.3 (2017-11-30) on MacOS High Sierra. The code works and the plot is produced without error. However, I am implementing heatmaply in a command line tool we're developing and as a result the printed output is messy. 

Does this warning need to be displayed? If so, is there a way for me to include code to suppress this warning from being printed? 

> Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
  dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 6): Library not loaded: /opt/X11/lib/libSM.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Resources/modules//R_X11.so
  Reason: image not found

I believe the warning is triggered because heatmaply looks for XQuartz to be installed but it is not installed on current Mac OSX. Manually installing XQuartz has been reported to solve the issue here [https://github.com/RevolutionAnalytics/RRO/issues/312] . However as heatmaply will be installed as a dependency of our command line tool, ideally heatmaply would install onto Mac OS without additional manual installation.

**Comment by Alanocallaghan** [comment] 2018-12-18 18:03
You can use suppressWarnings to not print warnings, though unfortunately it catches all warnings. I don't have access to a Mac so this might be hard to test but I can have a look later. This isn't something I'm aware of so would prefer to prevent it outright

On 18 Dec 2018 5:55 pm, gtollefson <notifications@github.com> wrote:

I receive the following warning when running the heatmaply() plotting function using heatmaply version 0.15.3 on R version 3.4.3 (2017-11-30) on MacOS High Sierra. The code works and the plot is produced without error. However, I am implementing heatmaply in a command line tool we're developing and as a result the printed output is messy.

Does this warning need to be displayed? If so, is there a way for me to include code to suppress this warning from being printed?

Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 6): Library not loaded: /opt/X11/lib/libSM.6.dylib
Referenced from: /Library/Frameworks/R.framework/Resources/modules//R_X11.so
Reason: image not found

I believe the warning is triggered because heatmaply looks for XQuartz to be installed but it is not installed on current Mac OSX. Manually installing XQuartz has been reported to solve the issue here [https://github.com/RevolutionAnalytics/RRO/issues/312<https://github.com/RevolutionAnalytics/RRO/issues/312>] . However as heatmaply will be installed as a dependency of our command line tool, ideally heatmaply would install onto Mac OS without additional manual installation.

**Comment by Alanocallaghan** [comment] 2018-12-19 14:51
> can you see which command is triggering the warning?
You can test this easily by setting `options(warn=2)` (this converts warnings to errors - reset using `options(warn=0)`). 

Also, are you using Microsoft R Open (given the related issue was specific to RRO)?

**Comment by gtollefson** [comment] 2018-12-19 16:20
Thanks for looking into this @Alanocallaghan and @talgalili. I am not using MRO - I'm using the following version:
R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

@talgalili the function runs fine without XQuartz and produces the plot I would expect. Also, it only produces the warning on the first time running the function in a session.

Interestingly, I do not get the error/warning message when I set `options(warn=2)` but does trigger the warning I run without setting this. Since setting warn=2 isn't working, I ran line by line to find the command and it looks like the error message comes from heatmaply(x). 

I've pasted the output from loading heatmaply (which produces two warnings) and the warning when I run the heatmaply() function.

> > library(heatmaply)
Loading required package: plotly
Loading required package: ggplot2

Attaching package: ‘plotly’

The following object is masked from ‘package:ggplot2’:

    last_plot

The following object is masked from ‘package:stats’:

    filter

The following object is masked from ‘package:graphics’:

    layout

Loading required package: viridis
Loading required package: viridisLite

======================
Welcome to heatmaply version 0.15.3

Type citation('heatmaply') for how to cite the package.
Type ?heatmaply for the main documentation.

The github page is: https://github.com/talgalili/heatmaply/
Please submit your suggestions and bug-reports at: https://github.com/talgalili/heatmaply/issues
Or contact: <tal.galili@gmail.com>
======================

Warning messages:
1: package ‘ggplot2’ was built under R version 3.4.4 
2: package ‘viridis’ was built under R version 3.4.4 

> heatmaply(gt_num_array_1)
Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
  dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 6): Library not loaded: /opt/X11/lib/libSM.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Resources/modules//R_X11.so
  Reason: image not found

**Comment by gtollefson** [comment] 2018-12-19 16:40
> Can you post what this returns in your R shell? `.Platform$GUI`
Returns: 

[1] "X11"

**Comment by gtollefson** [comment] 2018-12-19 16:42
> Also, could you try adding the argument `plot_method="plotly"` to your call to `heatmaply`, and then check if the warning still occurs?

The warning does not occur when I add this argument to the heatmaply() function.

**Comment by Alanocallaghan** [comment] 2018-12-19 16:43
Okay I think I know the issue! Great.

**Comment by Alanocallaghan** [comment] 2018-12-19 16:56
If you run this line, does it reproduce the warning?
```r
grDevices::png()
```

**Comment by gtollefson** [comment] 2018-12-19 17:50
> If you run this line, does it reproduce the warning?
> 
> ```r
> grDevices::png()
> ```

When I run this line alone in the R shell it does not reproduce the warning.

**Comment by gtollefson** [comment] 2018-12-19 17:51
When I run this line alone in the R shell it does not reproduce the warning.

**Comment by Alanocallaghan** [comment] 2018-12-19 18:14
Hmm, curious. How about `grDevices::jpeg()`?

**Comment by Alanocallaghan** [comment] 2018-12-19 18:17
Or `grDevices::dev.list()`

**Comment by gtollefson** [comment] 2018-12-19 20:16
@Alanocallaghan this returns the following output (including several warnings) and plots correctly.

> library(plotly)
Loading required package: ggplot2
p <- ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, color=Species, shape=Species)) + 
    geom_point(size=6, alpha=0.6)
ggplotly(p)

Attaching package: ‘plotly’

The following object is masked from ‘package:ggplot2’:

    last_plot

The following object is masked from ‘package:stats’:

    filter

The following object is masked from ‘package:graphics’:

    layout

Warning message:
package ‘ggplot2’ was built under R version 3.4.4 
> p <- ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, color=Species, shape=Species)) + 
+     geom_point(size=6, alpha=0.6)
> ggplotly(p)

**Comment by Alanocallaghan** [comment] 2018-12-19 20:19
I only see one warning there, and not the relevant one! Quite confusing. 

btw, the "package ‘X’ was built under R version 3.4.4" warnings can be fixed by re-installing package X.

**Comment by talgalili** [comment] 2019-08-17 05:15
This bug seems not updated (not reproducible?!).
Can we close this issue?

**Comment by Alanocallaghan** [comment] 2019-08-19 11:05
Couldn't get to the bottom of this, and it didn't affect output, so yep

**Closed by Alanocallaghan** 2019-08-19 11:05 UTC
